leftnav:
- identifier: d13a03ad-cdf4-4186-ac9e-84c8b5ec5379
  name: MIT Climate Primer website
  pageRef: /external-resources/mit-climate-primer-website_d13a03ad-cdf4-4186-ac9e-84c8b5ec5379
  weight: 1000
